export const DIM_LABELS: Record<string, string> = {
  hook:         "Hook",
  clarity:      "Clarity",
  seo_ready:    "SEO ready",
  depth:        "Depth",
  virality:     "Virality",
  brevity:      "Brevity",
  authority:    "Authority",
  engagement:   "Engagement",
  subject_line: "Subject line",
  value:        "Value",
  cta:          "CTA",
  subjects:     "Subjects",
  narrative:    "Narrative",
};
